//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.12.15 at 10:27:08 AM CET 
//


package java_xml_json.entities.news;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the fr.diginamic.jaxb.bean package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: fr.diginamic.jaxb.bean
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Datas }
     * 
     */
    public Datas createDatas() {
        return new Datas();
    }

    /**
     * Create an instance of {@link Datas.Pays }
     * 
     */
    public Datas.Pays createDatasPays() {
        return new Datas.Pays();
    }

    /**
     * Create an instance of {@link Datas.Pays.DonneesEconomiques }
     * 
     */
    public Datas.Pays.DonneesEconomiques createDatasPaysDonneesEconomiques() {
        return new Datas.Pays.DonneesEconomiques();
    }

    /**
     * Create an instance of {@link Datas.Pays.DonneesDemographiques }
     * 
     */
    public Datas.Pays.DonneesDemographiques createDatasPaysDonneesDemographiques() {
        return new Datas.Pays.DonneesDemographiques();
    }

    /**
     * Create an instance of {@link Datas.Pays.DateDeReleve }
     * 
     */
    public Datas.Pays.DateDeReleve createDatasPaysDateDeReleve() {
        return new Datas.Pays.DateDeReleve();
    }

    /**
     * Create an instance of {@link Datas.Pays.DonneesEconomiques.Pib }
     * 
     */
    public Datas.Pays.DonneesEconomiques.Pib createDatasPaysDonneesEconomiquesPib() {
        return new Datas.Pays.DonneesEconomiques.Pib();
    }

    /**
     * Create an instance of {@link Datas.Pays.DonneesDemographiques.Population }
     * 
     */
    public Datas.Pays.DonneesDemographiques.Population createDatasPaysDonneesDemographiquesPopulation() {
        return new Datas.Pays.DonneesDemographiques.Population();
    }

    /**
     * Create an instance of {@link Datas.Pays.DonneesDemographiques.Fecondite }
     * 
     */
    public Datas.Pays.DonneesDemographiques.Fecondite createDatasPaysDonneesDemographiquesFecondite() {
        return new Datas.Pays.DonneesDemographiques.Fecondite();
    }

}
